# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
#highlighter: rouge 

gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-redirect-from

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  #enable_coderay: true
